version: 0.2

phases:
  build:
    commands:
      - mvn test
  post_build:
    commands:
      - mvn package
artifacts:
  files:
    - '*.jar'
  base-directory: 'target'
cache:
  paths:
    - '/root/.m2/**/*'

